// ── Supabase setup ────────────────────────────────────────────────────────────
const USING_SUPABASE = SUPABASE_URL !== 'YOUR_SUPABASE_URL';
const db = USING_SUPABASE
  ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY)
  : null;
const TABLE  = 'cards';
const BUCKET = 'card-images';

// ── State ─────────────────────────────────────────────────────────────────────
let isAdmin         = false;
let allCards        = [...CARDS];
let editingId       = null;
let currentOccasion = null;
let currentYear     = null;
let pendingSvg      = null; // SVG generated by Claude, waiting to be saved

const GROUPS = [
  { key: "Father's Day", icon: '👔', label: "Father's Day" },
  { key: "Birthday",     icon: '🎂', label: "Birthday"     },
  { key: "Christmas",    icon: '🎄', label: "Christmas"    },
  { key: "Other",        icon: '🎁', label: "Other"        },
];

// ── Auth ──────────────────────────────────────────────────────────────────────
document.getElementById('unlock-btn').addEventListener('click', tryUnlock);
document.getElementById('password-input').addEventListener('keydown', e => {
  if (e.key === 'Enter') tryUnlock();
});

async function tryUnlock() {
  const val = document.getElementById('password-input').value;
  if (val !== VIEW_PASSWORD && val !== ADMIN_PASSWORD) {
    document.getElementById('lock-error').classList.remove('hidden');
    return;
  }
  document.getElementById('lock-screen').classList.add('hidden');

  if (val === ADMIN_PASSWORD) {
    activateAdmin();
  } else {
    document.getElementById('admin-btn').classList.add('hidden');
    const label = document.getElementById('logged-in-label');
    label.innerHTML = 'Logged in as: <strong>Best Dad Ever</strong>';
    label.classList.remove('hidden');
  }

  await loadCards();
  renderGallery();
  document.getElementById('app').classList.remove('hidden');
}

document.getElementById('lock-btn').addEventListener('click', () => {
  isAdmin = false;
  document.getElementById('add-card-btn').classList.add('hidden');
  document.getElementById('admin-btn').classList.remove('hidden');
  document.getElementById('admin-btn').textContent = 'Admin';
  document.getElementById('logged-in-label').classList.add('hidden');
  document.getElementById('app').classList.add('hidden');
  document.getElementById('lock-screen').classList.remove('hidden');
  document.getElementById('password-input').value = '';
  document.getElementById('lock-error').classList.add('hidden');
  showHomeScreen();
});

// ── Admin ─────────────────────────────────────────────────────────────────────
document.getElementById('admin-btn').addEventListener('click', () => {
  if (isAdmin) { deactivateAdmin(); return; }
  showModal('admin-modal');
  setTimeout(() => document.getElementById('admin-password-input').focus(), 50);
});

document.getElementById('admin-cancel-btn').addEventListener('click', () => hideModal('admin-modal'));
document.getElementById('admin-password-input').addEventListener('keydown', e => {
  if (e.key === 'Enter') confirmAdmin();
});
document.getElementById('admin-confirm-btn').addEventListener('click', confirmAdmin);

function confirmAdmin() {
  if (document.getElementById('admin-password-input').value === ADMIN_PASSWORD) {
    activateAdmin();
    hideModal('admin-modal');
  } else {
    document.getElementById('admin-error').classList.remove('hidden');
  }
}

function activateAdmin() {
  isAdmin = true;
  document.getElementById('add-card-btn').classList.remove('hidden');
  document.getElementById('admin-btn').classList.add('hidden');
  const label = document.getElementById('logged-in-label');
  label.innerHTML = 'Logged in as: <strong>1st Spawn of Darren</strong>';
  label.classList.remove('hidden');
  renderGallery();
}

function deactivateAdmin() {
  isAdmin = false;
  document.getElementById('add-card-btn').classList.add('hidden');
  document.getElementById('admin-btn').classList.remove('hidden');
  document.getElementById('logged-in-label').classList.add('hidden');
  renderGallery();
}

// ── Load cards ────────────────────────────────────────────────────────────────
async function loadCards() {
  if (!USING_SUPABASE) return; // use cards.js defaults
  const { data, error } = await db.from(TABLE).select('*').order('year', { ascending: false });
  if (error) { console.error('Supabase load error:', error); return; }
  allCards = data || [];
}

// ── Screen navigation ─────────────────────────────────────────────────────────
function showHomeScreen() {
  document.getElementById('home-screen').classList.remove('hidden');
  document.getElementById('card-screen').classList.add('hidden');
  document.getElementById('back-btn').classList.add('hidden');
  currentOccasion = null;
  currentYear = null;
}

function showCardScreen(occasion) {
  currentOccasion = occasion;
  document.getElementById('home-screen').classList.add('hidden');
  document.getElementById('card-screen').classList.remove('hidden');
  document.getElementById('back-btn').classList.remove('hidden');
  renderCardScreen();
}

document.getElementById('back-btn').addEventListener('click', showHomeScreen);

// ── Gallery ───────────────────────────────────────────────────────────────────
function renderGallery() {
  const main = document.getElementById('main-content');
  main.innerHTML = '';
  const hasAny = allCards.length > 0;
  document.getElementById('empty-msg').classList.add('hidden');

  GROUPS.forEach(group => {
    const cards = allCards.filter(c => c.occasion === group.key);

    const section = document.createElement('section');
    section.className = 'group';
    section.innerHTML = `
      <div class="group-header">
        <span class="group-icon">${group.icon}</span>
        <h2 class="group-title">${group.label}</h2>
        <span class="group-count">${cards.length} card${cards.length !== 1 ? 's' : ''}</span>
      </div>
      <div class="group-grid"></div>
      ${cards.length === 0 ? `<p class="empty-group">${isAdmin ? 'No cards yet — add one!' : 'Coming soon ✦'}</p>` : ''}
    `;

    const grid = section.querySelector('.group-grid');
    [...cards].sort((a, b) => b.year - a.year).forEach(card => {
      const tile = document.createElement('div');
      tile.className = 'card';
      const imgHtml = card.image_url
        ? `<img class="card-img" src="${card.image_url}" alt="" loading="lazy" />`
        : `<div class="card-placeholder">
             <span class="card-placeholder-icon">${group.icon}</span>
             <div class="card-placeholder-lines">
               <div class="card-placeholder-line"></div>
               <div class="card-placeholder-line"></div>
               <div class="card-placeholder-line"></div>
             </div>
           </div>`;
      tile.innerHTML = `
        ${imgHtml}
        <div class="card-body">
          ${isAdmin
            ? `<div class="card-year">${card.year}</div><div class="card-snippet">${card.message || ''}</div>`
            : `<div class="card-cta">CLICK TO VIEW</div>`}
        </div>
      `;
      tile.addEventListener('click', () => showCardScreen(group.key));
      grid.appendChild(tile);
    });

    main.appendChild(section);
  });
}

// ── Card view screen ──────────────────────────────────────────────────────────
function renderCardScreen() {
  const group = GROUPS.find(g => g.key === currentOccasion);
  const cards = allCards.filter(c => c.occasion === currentOccasion).sort((a, b) => b.year - a.year);

  // Year bar
  const yearBar = document.getElementById('year-bar');
  yearBar.innerHTML = '';
  if (!currentYear || !cards.find(c => c.year === currentYear)) {
    currentYear = cards[0]?.year ?? null;
  }
  cards.forEach(card => {
    const pill = document.createElement('button');
    pill.className = 'year-pill' + (card.year === currentYear ? ' active' : '');
    pill.textContent = card.year;
    pill.addEventListener('click', () => { currentYear = card.year; renderCardScreen(); });
    yearBar.appendChild(pill);
  });

  const selected = cards.find(c => c.year === currentYear);
  const content = document.querySelector('.card-view-content');
  content.innerHTML = '';
  if (!selected) return;

  if (selected.image_url) {
    const img = document.createElement('img');
    img.id = 'view-image';
    img.src = selected.image_url;
    img.alt = '';
    content.appendChild(img);
  }

  const hint = document.createElement('p');
  hint.className = 'card-tap-hint';
  hint.textContent = 'Tap the card to open it';
  content.appendChild(hint);

  const scene = document.createElement('div');
  scene.className = 'card-3d-scene';
  const W = Math.min(360, window.innerWidth * 0.88);
  const H = W * (480 / 360);
  scene.style.cssText = `perspective:1400px;width:${W}px;height:${H}px;margin-bottom:36px;cursor:pointer;position:relative;`;
  const frontContent = selected.card_svg
    ? `<div class="card-front-svg" style="position:absolute;inset:0;z-index:1;">${selected.card_svg}</div>`
    : `<div class="card-front-border"></div>
       <div class="card-front-corner tl"></div><div class="card-front-corner tr"></div>
       <div class="card-front-corner bl"></div><div class="card-front-corner br"></div>
       <div class="card-front-icon">${group.icon}</div>
       <div class="card-front-occasion">${selected.occasion}</div>
       <div class="card-front-year">${selected.year}</div>`;

  scene.innerHTML = `
    <div class="card-3d" id="card3d" style="width:${W}px;height:${H}px;position:relative;transform-style:preserve-3d;transition:transform 0.75s ease-in-out;box-shadow:0 20px 60px rgba(0,0,0,0.6);">
      <div class="card-face card-front ${selected.card_svg ? 'card-front--svg' : ''}" id="view-card-front" title="Click to enlarge" style="position:absolute;inset:0;overflow:hidden;border-radius:6px 14px 14px 6px;backface-visibility:hidden;-webkit-backface-visibility:hidden;${selected.card_svg ? 'background:none;' : ''}">${frontContent}</div>
      <div class="card-face card-back">
        <div class="card-back-lines">${Array(10).fill('<div class="card-back-line"></div>').join('')}</div>
        <div class="card-back-top-ornament">— ✦ —</div>
        <div class="card-back-message">${selected.message || ''}</div>
        <div class="card-back-signature">With love ♥</div>
      </div>
    </div>
  `;
  scene.addEventListener('click', () => {
    const card3d = scene.querySelector('.card-3d');
    card3d.classList.toggle('open');
    hint.textContent = card3d.classList.contains('open') ? 'Tap to close' : 'Tap the card to open it';
  });
  content.appendChild(scene);

  if (isAdmin) {
    const adminActions = document.createElement('div');
    adminActions.className = 'view-admin-actions';
    adminActions.innerHTML = `
      <button class="btn-secondary" id="view-edit-btn">Edit</button>
      <button class="btn-danger" id="view-delete-btn">Delete</button>
    `;
    adminActions.querySelector('#view-edit-btn').onclick = () => openCardModal(selected);
    adminActions.querySelector('#view-delete-btn').onclick = () => deleteCard(selected);
    content.appendChild(adminActions);
  }
}

// ── Card designer ─────────────────────────────────────────────────────────────
const BG_PALETTES = [
  { label:'Deep Navy',    bg1:'#0a0f1e', bg2:'#1a2540' },
  { label:'Midnight',     bg1:'#050505', bg2:'#0c0c14' },
  { label:'Deep Forest',  bg1:'#040e08', bg2:'#0d2010' },
  { label:'Burgundy',     bg1:'#100408', bg2:'#1e0a14' },
  { label:'Deep Ocean',   bg1:'#040c14', bg2:'#082030' },
  { label:'Twilight',     bg1:'#0a0414', bg2:'#180828' },
  { label:'Charcoal',     bg1:'#100e08', bg2:'#1c1a12' },
  { label:'Emerald Deep', bg1:'#040e0a', bg2:'#0a1e12' },
];
const ACCENT_PALETTES = [
  { label:'Gold',      color:'#c9a84c', text:'#f0e8d0' },
  { label:'Rose Gold', color:'#c8907a', text:'#f5e0d8' },
  { label:'Silver',    color:'#a0aab8', text:'#dde4ee' },
  { label:'Emerald',   color:'#4ac990', text:'#b0f0e0' },
  { label:'Amethyst',  color:'#9070c0', text:'#e0d0f8' },
  { label:'Coral',     color:'#c87060', text:'#f5d8d0' },
  { label:'Sapphire',  color:'#6090c8', text:'#d0e0f8' },
  { label:'Copper',    color:'#c88050', text:'#f0dcc0' },
];
const FONTS = [
  { id:'Georgia',              label:'Classic' },
  { id:'Palatino Linotype',    label:'Palatino' },
  { id:'Times New Roman',      label:'Times'    },
  { id:'Garamond',             label:'Garamond' },
];

let selectedTemplateId = CARD_TEMPLATES[0].id;
let designCfg = {
  bg1: CARD_TEMPLATES[0].defaultBg1, bg2: CARD_TEMPLATES[0].defaultBg2,
  accent: CARD_TEMPLATES[0].defaultAccent, textColor: CARD_TEMPLATES[0].defaultText,
  stars:true, border:true, corners:true, motif:true, divider:true, tagline:'', font:'Georgia',
};
let aiChatHistory = [];

document.getElementById('add-card-btn').addEventListener('click', () => openCardModal(null));

function openCardModal(card) {
  editingId  = card ? (card.id ?? card._index) : null;
  pendingSvg = card?.card_svg || null;
  document.getElementById('card-modal-title').textContent = card ? 'Edit Card' : 'Design a Card';
  document.getElementById('card-occasion').value = card ? card.occasion : "Father's Day";
  document.getElementById('card-year').value = card ? card.year : new Date().getFullYear();
  document.getElementById('card-message').value = card ? card.message : '';
  document.getElementById('card-tagline').value = '';
  document.getElementById('card-error').classList.add('hidden');
  document.getElementById('mini-3d-card').classList.remove('open');
  ['el-stars','el-border','el-corners','el-motif','el-divider'].forEach(id =>
    document.getElementById(id).checked = true);

  const tmpl = CARD_TEMPLATES[0];
  selectedTemplateId = tmpl.id;
  designCfg = { bg1:tmpl.defaultBg1, bg2:tmpl.defaultBg2, accent:tmpl.defaultAccent,
    textColor:tmpl.defaultText, stars:true, border:true, corners:true, motif:true, divider:true, tagline:'', font:'Georgia' };

  aiChatHistory = [];
  document.getElementById('ai-chat-log').innerHTML =
    '<div class="chat-msg chat-msg--assistant">Tell me what you\'re going for — a mood, a vibe, a memory — and I\'ll set it all up for you.</div>';

  if (card?.card_svg) document.getElementById('mini-front').innerHTML = card.card_svg;

  buildDesignerUI();
  updatePreview();
  showModal('card-modal');
}

function buildDesignerUI() {
  const grid = document.getElementById('tmpl-thumb-grid');
  grid.innerHTML = CARD_TEMPLATES.map(t => {
    const mini = t.render({ bg1:t.defaultBg1, bg2:t.defaultBg2, accent:t.defaultAccent,
      textColor:t.defaultText, stars:true, border:true, corners:true, motif:true, divider:false,
      tagline:'', font:'Georgia', occasion:'', year:'' });
    return `<button class="tmpl-thumb ${t.id===selectedTemplateId?'active':''}" data-tmpl="${t.id}" title="${t.name}">
      <div class="tmpl-thumb-img">${mini}</div>
      <span>${t.name}</span>
    </button>`;
  }).join('');
  grid.querySelectorAll('.tmpl-thumb').forEach(btn => {
    btn.addEventListener('click', () => {
      selectedTemplateId = btn.dataset.tmpl;
      const t = CARD_TEMPLATES.find(t => t.id === selectedTemplateId);
      designCfg.bg1 = t.defaultBg1; designCfg.bg2 = t.defaultBg2;
      designCfg.accent = t.defaultAccent; designCfg.textColor = t.defaultText;
      grid.querySelectorAll('.tmpl-thumb').forEach(b => b.classList.toggle('active', b===btn));
      buildBgSwatches(); buildAccentSwatches();
      updatePreview();
    });
  });
  buildBgSwatches();
  buildAccentSwatches();
  buildFontRow();
}

function buildBgSwatches() {
  const row = document.getElementById('bg-swatches');
  row.innerHTML = BG_PALETTES.map((p,i) =>
    `<button class="color-swatch ${p.bg1===designCfg.bg1?'active':''}" data-i="${i}" title="${p.label}"
      style="background:linear-gradient(135deg,${p.bg2},${p.bg1})"></button>`
  ).join('');
  row.querySelectorAll('.color-swatch').forEach(btn => btn.addEventListener('click', () => {
    const p = BG_PALETTES[+btn.dataset.i];
    designCfg.bg1 = p.bg1; designCfg.bg2 = p.bg2;
    row.querySelectorAll('.color-swatch').forEach(b => b.classList.toggle('active', b===btn));
    updatePreview();
  }));
}

function buildAccentSwatches() {
  const row = document.getElementById('accent-swatches');
  row.innerHTML = ACCENT_PALETTES.map((p,i) =>
    `<button class="color-swatch ${p.color===designCfg.accent?'active':''}" data-i="${i}" title="${p.label}"
      style="background:${p.color}"></button>`
  ).join('');
  row.querySelectorAll('.color-swatch').forEach(btn => btn.addEventListener('click', () => {
    const p = ACCENT_PALETTES[+btn.dataset.i];
    designCfg.accent = p.color; designCfg.textColor = p.text;
    row.querySelectorAll('.color-swatch').forEach(b => b.classList.toggle('active', b===btn));
    updatePreview();
  }));
}

function buildFontRow() {
  const row = document.getElementById('font-row');
  row.innerHTML = FONTS.map(f =>
    `<button class="font-btn ${f.id===designCfg.font?'active':''}" data-font="${f.id}"
      style="font-family:${f.id},Georgia,serif">${f.label}</button>`
  ).join('');
  row.querySelectorAll('.font-btn').forEach(btn => btn.addEventListener('click', () => {
    designCfg.font = btn.dataset.font;
    row.querySelectorAll('.font-btn').forEach(b => b.classList.toggle('active', b===btn));
    updatePreview();
  }));
}

function updatePreview() {
  const tmpl = CARD_TEMPLATES.find(t => t.id === selectedTemplateId);
  const cfg = {
    ...designCfg,
    stars:   document.getElementById('el-stars').checked,
    border:  document.getElementById('el-border').checked,
    corners: document.getElementById('el-corners').checked,
    motif:   document.getElementById('el-motif').checked,
    divider: document.getElementById('el-divider').checked,
    tagline: document.getElementById('card-tagline').value,
    occasion: document.getElementById('card-occasion').value,
    year:    document.getElementById('card-year').value || new Date().getFullYear(),
  };
  const svg = tmpl.render(cfg);
  pendingSvg = svg;
  document.getElementById('mini-front').innerHTML = svg;
  document.getElementById('mini-message-text').textContent =
    document.getElementById('card-message').value || 'Your message will appear here';
}

['card-occasion','card-year','card-message','card-tagline'].forEach(id =>
  document.getElementById(id).addEventListener('input', updatePreview));
['el-stars','el-border','el-corners','el-motif','el-divider'].forEach(id =>
  document.getElementById(id).addEventListener('change', updatePreview));

document.getElementById('mini-3d-scene').addEventListener('click', () =>
  document.getElementById('mini-3d-card').classList.toggle('open'));

document.getElementById('randomize-btn').addEventListener('click', () => {
  selectedTemplateId = CARD_TEMPLATES[Math.floor(Math.random()*CARD_TEMPLATES.length)].id;
  const bg = BG_PALETTES[Math.floor(Math.random()*BG_PALETTES.length)];
  const ac = ACCENT_PALETTES[Math.floor(Math.random()*ACCENT_PALETTES.length)];
  designCfg.bg1 = bg.bg1; designCfg.bg2 = bg.bg2;
  designCfg.accent = ac.color; designCfg.textColor = ac.text;
  designCfg.font = FONTS[Math.floor(Math.random()*FONTS.length)].id;
  buildDesignerUI(); updatePreview();
});

// ── AI design assistant ───────────────────────────────────────────────────────
async function sendToAI() {
  const input = document.getElementById('ai-chat-input');
  const text  = input.value.trim();
  if (!text) return;
  appendAiMsg('user', text);
  input.value = '';
  document.getElementById('ai-send-btn').disabled = true;
  document.getElementById('ai-loading').classList.remove('hidden');
  aiChatHistory.push({ role:'user', content:text });
  try {
    const res = await fetch('/api/generate-card', {
      method:'POST', headers:{'content-type':'application/json'},
      body: JSON.stringify({
        messages: aiChatHistory,
        occasion: document.getElementById('card-occasion').value,
        year:     document.getElementById('card-year').value || new Date().getFullYear(),
        templates: CARD_TEMPLATES.map(t => ({ id:t.id, name:t.name, defaultBg1:t.defaultBg1, defaultBg2:t.defaultBg2, defaultAccent:t.defaultAccent })),
        bgPalettes: BG_PALETTES, accentPalettes: ACCENT_PALETTES,
      }),
    });
    const data = await res.json();
    if (!res.ok) throw new Error(data.detail || data.error || 'Error');
    aiChatHistory.push({ role:'assistant', content:JSON.stringify(data) });
    appendAiMsg('assistant', data.reply || '✦');
    if (data.template && CARD_TEMPLATES.find(t => t.id===data.template)) selectedTemplateId = data.template;
    if (data.bg)     { designCfg.bg1 = data.bg.bg1; designCfg.bg2 = data.bg.bg2; }
    if (data.accent) { const ap = ACCENT_PALETTES.find(p => p.color===data.accent); designCfg.accent = data.accent; designCfg.textColor = ap?.text || '#f0e8d0'; }
    if (data.message) document.getElementById('card-message').value = data.message;
    if (data.tagline) document.getElementById('card-tagline').value = data.tagline;
    buildDesignerUI(); updatePreview();
  } catch(err) {
    appendAiMsg('assistant', 'Something went wrong: ' + err.message);
  } finally {
    document.getElementById('ai-send-btn').disabled = false;
    document.getElementById('ai-loading').classList.add('hidden');
  }
}

function appendAiMsg(role, text) {
  const log = document.getElementById('ai-chat-log');
  const el = document.createElement('div');
  el.className = 'chat-msg chat-msg--' + role;
  el.textContent = text;
  log.appendChild(el);
  log.scrollTop = log.scrollHeight;
}

document.getElementById('ai-send-btn').addEventListener('click', sendToAI);
document.getElementById('ai-chat-input').addEventListener('keydown', e => {
  if (e.key==='Enter' && !e.shiftKey) { e.preventDefault(); sendToAI(); }
});

document.getElementById('card-cancel-btn').addEventListener('click', () => hideModal('card-modal'));
document.getElementById('card-modal').addEventListener('click', e => { if (e.target.id==='card-modal') hideModal('card-modal'); });


// lightbox
document.addEventListener('click', e => {
  if (e.target.closest('#view-card-front')) {
    const svg = document.querySelector('#view-card-front svg');
    if (!svg) return;
    document.getElementById('svg-lightbox-inner').innerHTML = svg.outerHTML;
    document.getElementById('svg-lightbox').classList.remove('hidden');
  }
  if (e.target.id === 'svg-lightbox') {
    document.getElementById('svg-lightbox').classList.add('hidden');
  }
});

document.getElementById('card-save-btn').addEventListener('click', saveCard);

async function saveCard() {
  const occasion = document.getElementById('card-occasion').value;
  const year     = parseInt(document.getElementById('card-year').value, 10);
  const message  = document.getElementById('card-message').value.trim();
  const errEl    = document.getElementById('card-error');
  if (!year || !message) {
    errEl.textContent = 'Please fill in the year and message.';
    errEl.classList.remove('hidden');
    return;
  }

  const saveBtn = document.getElementById('card-save-btn');
  saveBtn.disabled = true;
  saveBtn.textContent = 'Saving…';

  try {
    const payload = { occasion, year, message, image_url: null, image_path: null, card_svg: pendingSvg || null };

    if (USING_SUPABASE) {
      if (editingId !== null) {
        const { error } = await db.from(TABLE).update(payload).eq('id', editingId);
        if (error) throw error;
      } else {
        const { error } = await db.from(TABLE).insert(payload);
        if (error) throw error;
      }
      await loadCards();
    } else {
      // Fallback: session-only (no Supabase configured)
      if (editingId !== null) {
        const idx = allCards.findIndex((c, i) => (c.id ?? i) === editingId);
        if (idx !== -1) allCards[idx] = { ...allCards[idx], ...payload };
      } else {
        allCards.push({ ...payload, _index: allCards.length });
      }
    }

    hideModal('card-modal');
    renderGallery();
    if (currentOccasion) renderCardScreen();
    if (!USING_SUPABASE) showNotice('Card saved this session only. Set up Supabase in config.js to make cards permanent.');
  } catch (err) {
    console.error(err);
    errEl.textContent = 'Something went wrong. Check your Supabase config.';
    errEl.classList.remove('hidden');
  } finally {
    saveBtn.disabled = false;
    saveBtn.textContent = 'Save Card';
  }
}

async function deleteCard(card) {
  if (!confirm(`Delete this ${card.occasion} card from ${card.year}?`)) return;
  if (USING_SUPABASE) {
    if (card.image_path) await db.storage.from(BUCKET).remove([card.image_path]);
    const { error } = await db.from(TABLE).delete().eq('id', card.id);
    if (error) { alert('Failed to delete.'); return; }
    await loadCards();
  } else {
    allCards = allCards.filter(c => c !== card);
  }
  const remaining = allCards.filter(c => c.occasion === currentOccasion);
  if (remaining.length === 0) { showHomeScreen(); }
  else { currentYear = null; renderCardScreen(); }
  renderGallery();
}

// ── Helpers ───────────────────────────────────────────────────────────────────
function showModal(id) { document.getElementById(id).classList.remove('hidden'); }
function hideModal(id) { document.getElementById(id).classList.add('hidden'); }

function showNotice(msg) {
  let n = document.getElementById('notice');
  if (!n) {
    n = document.createElement('div');
    n.id = 'notice';
    n.style.cssText = `position:fixed;bottom:24px;left:50%;transform:translateX(-50%);
      background:#1e2840;border:1px solid #c9a84c;color:#e8c96a;padding:12px 24px;
      border-radius:8px;font-size:0.82rem;font-family:-apple-system,sans-serif;z-index:999;
      letter-spacing:0.04em;box-shadow:0 4px 20px rgba(0,0,0,0.5);max-width:90vw;text-align:center;`;
    document.body.appendChild(n);
  }
  n.textContent = msg;
  n.style.display = 'block';
  clearTimeout(n._t);
  n._t = setTimeout(() => { n.style.display = 'none'; }, 6000);
}
