// ── Supabase setup ────────────────────────────────────────────────────────────
const USING_SUPABASE = SUPABASE_URL !== 'YOUR_SUPABASE_URL';
const db = USING_SUPABASE
  ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY)
  : null;
const TABLE  = 'cards';
const BUCKET = 'card-images';

// ── State ─────────────────────────────────────────────────────────────────────
let isAdmin         = false;
let allCards        = [...CARDS];
let editingId       = null;
let currentOccasion = null;
let currentYear     = null;
let pendingSvg      = null; // SVG generated by Claude, waiting to be saved

const GROUPS = [
  { key: "Father's Day", icon: '👔', label: "Father's Day" },
  { key: "Birthday",     icon: '🎂', label: "Birthday"     },
  { key: "Christmas",    icon: '🎄', label: "Christmas"    },
  { key: "Other",        icon: '🎁', label: "Other"        },
];

// ── Auth ──────────────────────────────────────────────────────────────────────
document.getElementById('unlock-btn').addEventListener('click', tryUnlock);
document.getElementById('password-input').addEventListener('keydown', e => {
  if (e.key === 'Enter') tryUnlock();
});

async function tryUnlock() {
  const val = document.getElementById('password-input').value;
  if (val !== VIEW_PASSWORD && val !== ADMIN_PASSWORD) {
    document.getElementById('lock-error').classList.remove('hidden');
    return;
  }
  document.getElementById('lock-screen').classList.add('hidden');
  document.getElementById('app').classList.remove('hidden');

  if (val === ADMIN_PASSWORD) {
    activateAdmin();
  } else {
    document.getElementById('admin-btn').classList.add('hidden');
    document.getElementById('logged-in-label').classList.remove('hidden');
  }

  await loadCards();
  renderGallery();
}

document.getElementById('lock-btn').addEventListener('click', () => {
  isAdmin = false;
  document.getElementById('add-card-btn').classList.add('hidden');
  document.getElementById('admin-btn').classList.remove('hidden');
  document.getElementById('admin-btn').textContent = 'Admin';
  document.getElementById('logged-in-label').classList.add('hidden');
  document.getElementById('app').classList.add('hidden');
  document.getElementById('lock-screen').classList.remove('hidden');
  document.getElementById('password-input').value = '';
  document.getElementById('lock-error').classList.add('hidden');
  showHomeScreen();
});

// ── Admin ─────────────────────────────────────────────────────────────────────
document.getElementById('admin-btn').addEventListener('click', () => {
  if (isAdmin) { deactivateAdmin(); return; }
  showModal('admin-modal');
  setTimeout(() => document.getElementById('admin-password-input').focus(), 50);
});

document.getElementById('admin-cancel-btn').addEventListener('click', () => hideModal('admin-modal'));
document.getElementById('admin-password-input').addEventListener('keydown', e => {
  if (e.key === 'Enter') confirmAdmin();
});
document.getElementById('admin-confirm-btn').addEventListener('click', confirmAdmin);

function confirmAdmin() {
  if (document.getElementById('admin-password-input').value === ADMIN_PASSWORD) {
    activateAdmin();
    hideModal('admin-modal');
  } else {
    document.getElementById('admin-error').classList.remove('hidden');
  }
}

function activateAdmin() {
  isAdmin = true;
  document.getElementById('add-card-btn').classList.remove('hidden');
  document.getElementById('admin-btn').textContent = 'Exit Admin';
  renderGallery();
}

function deactivateAdmin() {
  isAdmin = false;
  document.getElementById('add-card-btn').classList.add('hidden');
  document.getElementById('admin-btn').textContent = 'Admin';
  renderGallery();
}

// ── Load cards ────────────────────────────────────────────────────────────────
async function loadCards() {
  if (!USING_SUPABASE) return; // use cards.js defaults
  const { data, error } = await db.from(TABLE).select('*').order('year', { ascending: false });
  if (error) { console.error('Supabase load error:', error); return; }
  allCards = data || [];
}

// ── Screen navigation ─────────────────────────────────────────────────────────
function showHomeScreen() {
  document.getElementById('home-screen').classList.remove('hidden');
  document.getElementById('card-screen').classList.add('hidden');
  document.getElementById('back-btn').classList.add('hidden');
  currentOccasion = null;
  currentYear = null;
}

function showCardScreen(occasion) {
  currentOccasion = occasion;
  document.getElementById('home-screen').classList.add('hidden');
  document.getElementById('card-screen').classList.remove('hidden');
  document.getElementById('back-btn').classList.remove('hidden');
  renderCardScreen();
}

document.getElementById('back-btn').addEventListener('click', showHomeScreen);

// ── Gallery ───────────────────────────────────────────────────────────────────
function renderGallery() {
  const main = document.getElementById('main-content');
  main.innerHTML = '';
  const hasAny = allCards.length > 0;
  document.getElementById('empty-msg').classList.add('hidden');

  GROUPS.forEach(group => {
    const cards = allCards.filter(c => c.occasion === group.key);

    const section = document.createElement('section');
    section.className = 'group';
    section.innerHTML = `
      <div class="group-header">
        <span class="group-icon">${group.icon}</span>
        <h2 class="group-title">${group.label}</h2>
        <span class="group-count">${cards.length} card${cards.length !== 1 ? 's' : ''}</span>
      </div>
      <div class="group-grid"></div>
      ${cards.length === 0 ? `<p class="empty-group">${isAdmin ? 'No cards yet — add one!' : 'Coming soon ✦'}</p>` : ''}
    `;

    const grid = section.querySelector('.group-grid');
    [...cards].sort((a, b) => b.year - a.year).forEach(card => {
      const tile = document.createElement('div');
      tile.className = 'card';
      const imgHtml = card.image_url
        ? `<img class="card-img" src="${card.image_url}" alt="" loading="lazy" />`
        : `<div class="card-placeholder">
             <span class="card-placeholder-icon">${group.icon}</span>
             <div class="card-placeholder-lines">
               <div class="card-placeholder-line"></div>
               <div class="card-placeholder-line"></div>
               <div class="card-placeholder-line"></div>
             </div>
           </div>`;
      tile.innerHTML = `
        ${imgHtml}
        <div class="card-body">
          ${isAdmin
            ? `<div class="card-year">${card.year}</div><div class="card-snippet">${card.message || ''}</div>`
            : `<div class="card-cta">CLICK TO VIEW</div>`}
        </div>
      `;
      tile.addEventListener('click', () => showCardScreen(group.key));
      grid.appendChild(tile);
    });

    main.appendChild(section);
  });
}

// ── Card view screen ──────────────────────────────────────────────────────────
function renderCardScreen() {
  const group = GROUPS.find(g => g.key === currentOccasion);
  const cards = allCards.filter(c => c.occasion === currentOccasion).sort((a, b) => b.year - a.year);

  // Year bar
  const yearBar = document.getElementById('year-bar');
  yearBar.innerHTML = '';
  if (!currentYear || !cards.find(c => c.year === currentYear)) {
    currentYear = cards[0]?.year ?? null;
  }
  cards.forEach(card => {
    const pill = document.createElement('button');
    pill.className = 'year-pill' + (card.year === currentYear ? ' active' : '');
    pill.textContent = card.year;
    pill.addEventListener('click', () => { currentYear = card.year; renderCardScreen(); });
    yearBar.appendChild(pill);
  });

  const selected = cards.find(c => c.year === currentYear);
  const content = document.querySelector('.card-view-content');
  content.innerHTML = '';
  if (!selected) return;

  if (selected.image_url) {
    const img = document.createElement('img');
    img.id = 'view-image';
    img.src = selected.image_url;
    img.alt = '';
    content.appendChild(img);
  }

  const hint = document.createElement('p');
  hint.className = 'card-tap-hint';
  hint.textContent = 'Tap the card to open it';
  content.appendChild(hint);

  const scene = document.createElement('div');
  scene.className = 'card-3d-scene';
  const frontContent = selected.card_svg
    ? `<div class="card-front-svg">${selected.card_svg}</div>`
    : `<div class="card-front-border"></div>
       <div class="card-front-corner tl"></div><div class="card-front-corner tr"></div>
       <div class="card-front-corner bl"></div><div class="card-front-corner br"></div>
       <div class="card-front-icon">${group.icon}</div>
       <div class="card-front-occasion">${selected.occasion}</div>
       <div class="card-front-year">${selected.year}</div>`;

  scene.innerHTML = `
    <div class="card-3d" id="card3d">
      <div class="card-face card-front">${frontContent}</div>
      <div class="card-face card-back">
        <div class="card-back-lines">${Array(10).fill('<div class="card-back-line"></div>').join('')}</div>
        <div class="card-back-top-ornament">— ✦ —</div>
        <div class="card-back-message">${selected.message || ''}</div>
        <div class="card-back-signature">With love ♥</div>
      </div>
    </div>
  `;
  scene.addEventListener('click', () => {
    const card3d = scene.querySelector('.card-3d');
    card3d.classList.toggle('open');
    hint.textContent = card3d.classList.contains('open') ? 'Tap to close' : 'Tap the card to open it';
  });
  content.appendChild(scene);

  if (isAdmin) {
    const adminActions = document.createElement('div');
    adminActions.className = 'view-admin-actions';
    adminActions.innerHTML = `
      <button class="btn-secondary" id="view-edit-btn">Edit</button>
      <button class="btn-danger" id="view-delete-btn">Delete</button>
    `;
    adminActions.querySelector('#view-edit-btn').onclick = () => openCardModal(selected);
    adminActions.querySelector('#view-delete-btn').onclick = () => deleteCard(selected);
    content.appendChild(adminActions);
  }
}

// ── Add / Edit card modal ─────────────────────────────────────────────────────
document.getElementById('add-card-btn').addEventListener('click', () => openCardModal(null));

function openCardModal(card) {
  editingId  = card ? (card.id ?? card._index) : null;
  pendingSvg = null;
  document.getElementById('card-modal-title').textContent = card ? 'Edit Card' : 'New Card';
  document.getElementById('card-occasion').value = card ? card.occasion : "Father's Day";
  document.getElementById('card-year').value = card ? card.year : new Date().getFullYear();
  document.getElementById('card-message').value = card ? card.message : '';
  document.getElementById('card-design-prompt').value = '';
  document.getElementById('card-error').classList.add('hidden');
  document.getElementById('design-preview-wrap').classList.add('hidden');
  document.getElementById('design-loading').classList.add('hidden');
  document.getElementById('design-svg-preview').innerHTML = '';

  // If editing a card that already has a generated SVG, show it
  if (card?.card_svg) {
    pendingSvg = card.card_svg;
    document.getElementById('design-svg-preview').innerHTML = card.card_svg;
    document.getElementById('design-preview-wrap').classList.remove('hidden');
  }

  showModal('card-modal');
  setTimeout(() => document.getElementById('card-message').focus(), 50);
}

// ── AI card generation ────────────────────────────────────────────────────────
async function generateDesign() {
  const prompt   = document.getElementById('card-design-prompt').value.trim();
  const occasion = document.getElementById('card-occasion').value;
  const year     = document.getElementById('card-year').value;
  if (!prompt) { showNotice('Enter a design description first.'); return; }

  const genBtn  = document.getElementById('generate-design-btn');
  const regenBtn = document.getElementById('regenerate-btn');
  const loading = document.getElementById('design-loading');
  const preview = document.getElementById('design-preview-wrap');

  genBtn.disabled  = true;
  if (regenBtn) regenBtn.disabled = true;
  loading.classList.remove('hidden');
  preview.classList.add('hidden');

  try {
    const res  = await fetch('/api/generate-card', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ prompt, occasion, year }),
    });
    const data = await res.json();
    if (!res.ok || !data.svg) throw new Error(data.error || 'No SVG returned');

    pendingSvg = data.svg;
    document.getElementById('design-svg-preview').innerHTML = data.svg;
    preview.classList.remove('hidden');
  } catch (err) {
    console.error(err);
    showNotice('Generation failed: ' + err.message);
  } finally {
    genBtn.disabled = false;
    if (regenBtn) regenBtn.disabled = false;
    loading.classList.add('hidden');
  }
}

document.getElementById('generate-design-btn').addEventListener('click', generateDesign);
document.addEventListener('click', e => {
  if (e.target.id === 'regenerate-btn') generateDesign();
});

document.getElementById('card-cancel-btn').addEventListener('click', () => hideModal('card-modal'));
document.getElementById('card-modal').addEventListener('click', e => { if (e.target.id === 'card-modal') hideModal('card-modal'); });

document.getElementById('card-image').addEventListener('change', e => {
  const file = e.target.files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = ev => {
    document.getElementById('card-image-preview').src = ev.target.result;
    document.getElementById('card-image-preview-wrap').classList.remove('hidden');
  };
  reader.readAsDataURL(file);
});

document.getElementById('card-image-remove').addEventListener('click', () => {
  document.getElementById('card-image').value = '';
  document.getElementById('card-image-preview-wrap').classList.add('hidden');
});

document.getElementById('card-save-btn').addEventListener('click', saveCard);

async function saveCard() {
  const occasion = document.getElementById('card-occasion').value;
  const year     = parseInt(document.getElementById('card-year').value, 10);
  const message  = document.getElementById('card-message').value.trim();
  const errEl    = document.getElementById('card-error');
  if (!year || !message) {
    errEl.textContent = 'Please fill in the year and message.';
    errEl.classList.remove('hidden');
    return;
  }

  const saveBtn = document.getElementById('card-save-btn');
  saveBtn.disabled = true;
  saveBtn.textContent = 'Saving…';

  try {
    let image_url  = null;
    let image_path = null;
    const imageFile = document.getElementById('card-image').files[0];

    if (USING_SUPABASE && imageFile) {
      const ext  = imageFile.name.split('.').pop();
      const path = `${Date.now()}.${ext}`;
      const { error: upErr } = await db.storage.from(BUCKET).upload(path, imageFile, { upsert: true });
      if (upErr) throw upErr;
      const { data: urlData } = db.storage.from(BUCKET).getPublicUrl(path);
      image_url  = urlData.publicUrl;
      image_path = path;

      // Remove old image if replacing
      const old = allCards.find(c => (c.id ?? c._index) === editingId);
      if (old?.image_path) await db.storage.from(BUCKET).remove([old.image_path]);
    }

    const payload = { occasion, year, message, image_url, image_path, card_svg: pendingSvg || null };

    if (USING_SUPABASE) {
      if (editingId !== null) {
        const { error } = await db.from(TABLE).update(payload).eq('id', editingId);
        if (error) throw error;
      } else {
        const { error } = await db.from(TABLE).insert(payload);
        if (error) throw error;
      }
      await loadCards();
    } else {
      // Fallback: session-only (no Supabase configured)
      if (editingId !== null) {
        const idx = allCards.findIndex((c, i) => (c.id ?? i) === editingId);
        if (idx !== -1) allCards[idx] = { ...allCards[idx], ...payload };
      } else {
        allCards.push({ ...payload, _index: allCards.length });
      }
    }

    hideModal('card-modal');
    renderGallery();
    if (currentOccasion) renderCardScreen();
    if (!USING_SUPABASE) showNotice('Card saved this session only. Set up Supabase in config.js to make cards permanent.');
  } catch (err) {
    console.error(err);
    errEl.textContent = 'Something went wrong. Check your Supabase config.';
    errEl.classList.remove('hidden');
  } finally {
    saveBtn.disabled = false;
    saveBtn.textContent = 'Save Card';
  }
}

async function deleteCard(card) {
  if (!confirm(`Delete this ${card.occasion} card from ${card.year}?`)) return;
  if (USING_SUPABASE) {
    if (card.image_path) await db.storage.from(BUCKET).remove([card.image_path]);
    const { error } = await db.from(TABLE).delete().eq('id', card.id);
    if (error) { alert('Failed to delete.'); return; }
    await loadCards();
  } else {
    allCards = allCards.filter(c => c !== card);
  }
  const remaining = allCards.filter(c => c.occasion === currentOccasion);
  if (remaining.length === 0) { showHomeScreen(); }
  else { currentYear = null; renderCardScreen(); }
  renderGallery();
}

// ── Helpers ───────────────────────────────────────────────────────────────────
function showModal(id) { document.getElementById(id).classList.remove('hidden'); }
function hideModal(id) { document.getElementById(id).classList.add('hidden'); }

function showNotice(msg) {
  let n = document.getElementById('notice');
  if (!n) {
    n = document.createElement('div');
    n.id = 'notice';
    n.style.cssText = `position:fixed;bottom:24px;left:50%;transform:translateX(-50%);
      background:#1e2840;border:1px solid #c9a84c;color:#e8c96a;padding:12px 24px;
      border-radius:8px;font-size:0.82rem;font-family:-apple-system,sans-serif;z-index:999;
      letter-spacing:0.04em;box-shadow:0 4px 20px rgba(0,0,0,0.5);max-width:90vw;text-align:center;`;
    document.body.appendChild(n);
  }
  n.textContent = msg;
  n.style.display = 'block';
  clearTimeout(n._t);
  n._t = setTimeout(() => { n.style.display = 'none'; }, 6000);
}
